# Generated by Django 4.2.7 on 2023-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("details", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="newsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("reporter", models.CharField(max_length=10)),
                ("company", models.CharField(max_length=50)),
                ("datetime", models.DateTimeField()),
                ("article", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
