# Generated by Django 4.2.7 on 2023-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("details", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="newsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=50)),
                ("reporter", models.CharField(blank=True, max_length=10)),
                ("company", models.CharField(blank=True, max_length=10)),
                ("created_datetime", models.DateTimeField()),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("article", models.TextField()),
                ("keywords", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
